services:
  - type: web
    name: lexaglot-site
    env: static
    buildCommand: npm install
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 